# docker-compose.aws.yml
version: "3"

services:
    master:
        build:
            context: .
            dockerfile: Dockerfile.master
        ports:
            - "5000:5000"
        environment:
            - FLASK_APP=app.py
            - FLASK_ENV=production
            - REDIS_HOST=${REDIS_HOST}
            - MONGODB_HOST=${MONGODB_HOST}
        restart: always

    worker:
        build:
            context: .
            dockerfile: Dockerfile.worker
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - MONGODB_HOST=${MONGODB_HOST}
        restart: always

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        restart: always

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        restart: always

volumes:
    redis_data:
    mongodb_data:
